### PR TITLE
A few commits - removes unneeded files, adds gulpfile and files & directories for flux and react

### PR DESCRIPTION
**Pull request by conrad**

### CODE REVIEW

**Comment by ClimbsRocks** [comment]
@mmconrad did you --rebase before making this pull request? It can't be automatically merged in the gui. It looks like you have some redundant work with deleting the _. files, and adding in some server stuff.

**Comment by conrad** [comment]
I did have those _. files deleted several days before and didn't know if I should add those back in once the change ended up in your pull request.

And I didn't rebase. I'll try to figure out how to fix this and will issue a new pull request.

**Comment by ClimbsRocks** [comment]
Yeah, I think if you'd just rebased it would handle all the uncertainty by
matching your commits up with the current master branch history and joining
them together. Let me know when the new version's ready!

**Comment by ClimbsRocks** [comment]
This looks like awesome progress! My open question at the moment before merging it in is how the server you have in here fits in with the server we're already working on.

**Comment by conrad** [comment]
Preston, I was talking to Christian when I saw your question.  I tried multiple times to delete that server, like the the _. files. But I had to abandon that effort for this pull request.  Those should be easy to delete now. Leave them. I will get them and do another pull request.

**Comment by ClimbsRocks** [comment]
awesome, just wanted to make sure we were all working on the same thing. merging now! thanks again for building out the infrastructure for our react app.

**Comment by conrad** [comment]
Just doing my job

**Pull request merged**
