### PR TITLE
adds pages and react components for login and submit

### PR DESCRIPTION
**Pull request by conrad**

### CODE REVIEW

**Comment by ClimbsRocks** [comment]
Looks good. I'm very impressed by how quickly you're picking up React. 

Two minor code cleanup notes: 
1. Could you add in newlines at the end of each file?
2. There is a file in public/js called untitled. Could you rename it?

**Comment by conrad** [comment]
Of course!

**Comment by ClimbsRocks** [comment]
Testing where new pull requests go and if they are automatically joined with existing pull requests from the same user.

**Comment by conrad** [comment]
So that's what happened... I got blocked from making a new one
...but also has a record of the one I was making

**Comment by ClimbsRocks** [comment]
oh darn, weird. alright, experiment over for now :)

**Pull request closed without merging**
